config/routes.rb
Rails.application.routes.draw do
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  get '/search' => 'search#search'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do

    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end


  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  is_impressionable counter_cache: true



end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }


end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :chats
  has_many :user_rooms
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!,except: [:top]

  def index
    @books = Book.all
    @rank_books = Book.order(impressions_count: 'DESC')
    @book_new = Book.new
    @user = current_user
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}

  end

  def create
    @books = Book.all
    @user = current_user
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = "successfully completed"
      redirect_to book_path(@book_new)
    else
      render :index
    end

  end

  def show
    @book = Book.find(params[:id])
    impressionist(@book, nil, unique: [:ip_address])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments.order(created_at: :desc)
    @books = Book.all
    @user = @book.user
    @book_new = Book.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully completed"
      redirect_to book_path(@book.id)
    else
      render("books/edit")
    end

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
  @user = User.find(params[:id])
  rooms = current_user.user_rooms.pluck(:room_id)
  user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

  if user_rooms.nil?
   @room = Room.new
   @room.save
   UserRoom.create(user_id: @user.id, room_id: @room.id)
   UserRoom.create(user_id: current_user.id, room_id: @room.id)
  else
   @room = user_rooms.room
  end

   @chats = @room.chats
   @chat = Chat.new(room_id: @room.id)
  end

  def create
   @chat = current_user.chats.new(chat_params)
   @chat.save
  end

 private

  def chat_params
   params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  before_action :authenticate_user!


  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @dates = search_for(@how, @model, @value)
  end

  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!,except: [:top]


  def index
    @users = User.all
    @book_new = Book.new
    @user = current_user


  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
    @books = @user.books.all

  end


  def edit
    @user = User.find(params[:id])
    if @user == current_user
       render :edit
    else
       redirect_to user_path(current_user)
    end
  end




  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully completed"
      redirect_to user_path(@user)
    else
      render("users/edit")
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <h2>User info</h2>

  <table class="table">

    <tbody>

      <tr>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      </tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>

      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>

      <tr>
        <th>follows</th>
        <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
      </tr>

      <tr>
        <th>
          <% unless current_user == user %>
          <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), class:"btn btn-success mt-2", method: :delete %>
          <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), class:"btn btn-success mt-2", method: :post %>
          <% end %>
          <% end %>
        </th>
        <% if (current_user.following? @user) && (@user.following? current_user) %>
        <% if current_user != user %>
          <%= link_to 'チャットする', chat_path(user.id) %>
        <% end %>
        <% end %>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" do %>
    <% end %>
  </div>

app/views/books/edit.html.erb
  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors
    <% @book.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
  <% if @book_new.errors.any? %>
    <%= @book_new.errors.count %>errors
    <% @book_new.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>


        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book-body" %>
        </div>
        <div class="form-group">
          <%= f.submit :commit, class:"btn btn-success", value:"Create Book" %>
        </div>
        <% end %>
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>

            <tr>
             <td>
               <%= link_to user_path(book.user.id) do %>
               <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
               <% end %>
            </td>
             <td>
               <%= link_to book_path(book.id) do %>
               <%= book.title %>
               <% end %>
             </td>
             <td>
               <%= book.body %>
             </td>
             <td id="favorite_buttons_<%= book.id %>">
               <%= render "favorites/favorite", book: book %>
             </td>
             <td>
               <%= link_to "#{book.book_comments.count}コメント", book_path(book.id) %>
             </td>
             <td>
               閲覧数：<%= book.impressions_count %>
             </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>

app/views/books/show.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>


        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book-body" %>
        </div>
        <div class="form-group">
          <%= f.submit :commit, class:"btn btn-success", value:"Create Book" %>
        </div>
        <% end %>
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
            <tr>
             <td>
               <%= link_to user_path(@user) do %>
               <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
               <br>
               <%= @user.name %>
               <% end %>
              </td>
             <td>
               <%= link_to book_path(@book) do %>
               <%= @book.title %>
               <% end %>
             </td>
             <td>
               <%= @book.body %>
             </td>
             <td id="favorite_buttons_<%= @book.id %>">
               <%= render "favorites/favorite", book: @book %>
             </td>
             <td>コメント件数:<%= @book.book_comments.count %></td>
             <td>閲覧数：<%= @book.impressions_count %></td>
             <% if user_signed_in? && current_user.id == @book.user_id %>
             <td>
               <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
             </td>
             <td>
               <%= link_to "Destroy", book_path(@book), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'delete ok?' } %>
             </td>
             <% end %>
            </tr>
        </tbody>
      </table>
      <%= render  "book_comments/index", book_comment: @book_comments, book: @book %>
      <%= render "book_comments/form", book_comment: @book_comment, book: @book %>
    </div>
    </div>
  </div>
</main>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h2>CHAT WITH <%= @user.name %></h2>

      <table class="message table">
        <thead>
          <tr>
            <th style="test-align: right; font-size: 20px;"><%= current_user.name %></th>
            <th style="test-align: left; font-size: 20px;"><%= @user.name %></th>
          </tr>
        </thead>
      </table>
        <% @chats.each do |chat| %>
         <% if chat.user_id == current_user.id %>
         <tbody>
           <tr>
             <th>
               <p style="test-align: right;"><%= chat.message %></p>
             </th>
             <th></th>
           </tr>
           <% else %>
           <tr>
             <th></th>
             <th>
               <p style="text-align: left;"><%= chat.message %></p>
             </th>
           </tr>
         </tbody>
         <% end %>
        <% end %>


        <%= form_with model: @chat, remote: true do |f| %>
          <%= f.text_field :message %>
          <%= f.hidden_field :room_id %>
          <%= f.submit "SEND", class:"btn btn-sm btn-success chat-btn" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
  <% if @user.errors.any? %>
    <%= @user.errors.count %>errors
    <% @user.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">

          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <label for="user-introduction">Introduction</label>
          <%= f.text_area :introduction, class:"form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>

　　　　<h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book-body" %>
        </div>
        <div class="form-group">
          <%= f.submit :commit, class:"btn btn-success", value:"Create Book" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
             <% @users.each do |user| %>
             <tr>

              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

              </td>
              <td>
                <%= user.name %>
              </td>
              <td>フォロー数: <%= user.followings.count %></td>
              <td>フォロワー数: <%= user.followers.count %></td>
              <td>
                <% unless current_user == user %>
                <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>
             </tr>
             <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', user: @user %>

　　　　<h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book-body" %>
        </div>
        <div class="form-group">
          <%= f.submit :commit, class:"btn btn-success", value:"Create Book" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
         <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
               <th></th>
               <th>Title</th>
               <th>Opinion</th>
               <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                   <%= link_to user_path(book.user) do %>
                   <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                   <% end %>
                  </td>
                  <td>
                   <%= link_to book_path(book) do %>
                   <%= book.title %>
                   <% end %>
                  </td>
                  <td>
                   <%= book.body %>
                  </td>
                  <td>
                    <%= link_to "#{book.book_comments.count}コメント", book_path(book.id) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>